'use client';

import { Canvas } from '@react-three/fiber';
import { StructureGraph } from '@/components/3d/StructureGraph';
import { Environment, OrbitControls } from '@react-three/drei';

export default function StructurePage() {
  return (
    <div className="space-y-12 animate-in fade-in duration-500">
      <div className="border-b border-platinum pb-6">
        <h1 className="text-3xl font-semibold text-graphite mb-3">Structure & Entities</h1>
        <p className="text-lg text-text-meta max-w-3xl leading-relaxed">
          Living Systems Intelligence | CytosAI Inc. (Delaware) acts as the primary holding company. Our operational structure is designed to isolate liability while facilitating seamless IP transfer between divisions.
        </p>
      </div>

      {/* 3D Structure Visualization */}
      <div className="h-[400px] bg-off-white border border-platinum rounded-xl overflow-hidden relative touch-none">
        <div className="absolute top-4 left-4 z-10">
          <span className="text-xs font-bold text-text-meta uppercase tracking-wider bg-white/80 backdrop-blur px-2 py-1 rounded">Interactive Model</span>
        </div>
        <Canvas camera={{ position: [0, 0, 8], fov: 45 }}>
           <ambientLight intensity={0.8} />
           <pointLight position={[10, 10, 10]} />
           <StructureGraph />
           <OrbitControls enableZoom={false} autoRotate autoRotateSpeed={1} />
           <Environment preset="studio" />
        </Canvas>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <h3 className="text-lg font-bold text-graphite mb-4">Tax & Jurisdiction</h3>
          <p className="text-text-meta text-sm leading-relaxed mb-4">
            The company utilizes a standard transfer pricing agreement between CytosAI Labs Ltd. (IP generation) and LSI Therapeutics LLC (Commercialization), compliant with OECD guidelines and Section 482 of the IRC.
          </p>
          <a href="#" className="text-steel-blue text-sm hover:underline">Download Tax Residency Certificate (2025) &rarr;</a>
        </div>
        <div>
           <h3 className="text-lg font-bold text-graphite mb-4">IP Assignment</h3>
           <p className="text-text-meta text-sm leading-relaxed">
             All intellectual property generated by employees is automatically assigned to CytosAI Labs Ltd. Cross-licensing agreements ensure LSI Therapeutics has exclusive commercial rights for key indication areas.
           </p>
        </div>
      </div>
    </div>
  );
}